### ISSUE TITLE
Making 3D in LGGL

### ISSUE THREAD

**Issue by CristeaAndreiFlavian** [zenith391/PowerHigh#2]
3D may potentially come in LGGL! But it is WIP!

**Comment by zenith391** [comment]
I don't think it will be the best thing to do. Since 3D in LGGL would be very slow. Because it will offer 0 hardware accelerations. I still can try to do that, but it will not be part of main project. More like another library

**Comment by zenith391** [comment]
Also, i forgot to say the issue don’t match project goals (2D), but thanks for the issue.
